### ISSUE TITLE
Create CONTRIBUTING.md File

### ISSUE THREAD

**Issue by csellis** [csellis/creativity-doanythingyouwant#4]
Need a contributing

**Comment by Sscuber03** [comment]
Does this file need to be created, and the normal rules of the contributing should be there, along with the names of the contributors?
If so, can this be assigned to me?

**Comment by AEllis86** [comment]
> Does this file need to be created, and the normal rules of the contributing should be there, along with the names of the contributors? If so, can this be assigned to me?

Yes, normal rules and I can assign to you.
